apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc # Name for the Redis data volume claim
spec:
  accessModes:
    - ReadWriteOnce # Suitable for single Redis instance data
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte
  # storageClassName: standard # Optional: Specify if needed
